# Generated by Django 4.2.5 on 2023-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libellium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('CO', models.FloatField()),
                ('O3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='plug',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
