# Generated by Django 4.2.5 on 2023-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_libellium_plug'),
    ]

    operations = [
        migrations.AddField(
            model_name='libellium',
            name='HUM',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libellium',
            name='PRES',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libellium',
            name='TC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
