# Generated by Django 4.2.5 on 2023-09-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_libellium_hum_libellium_pres_libellium_tc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plug',
        ),
    ]
